### ISSUE TITLE
Paper: Choose a Venue

### ISSUE THREAD

**Issue by ashepherd** [Semantic-Observations/obs-models#1]
SWJ: but maybe too technical
Ocean Tech Journal
EOS (doesn’t target right type of article)
PLOS ONE
Earth Science Informatics
PeerJ
PeerJ Comp Sci
F1000 Research
CEUS: http://www.journals.elsevier.com/computers-environment-and-urban-systems/ 
Journal of Web Semantics
Applied Ontology
Open Access
Open Access
PLOS Comp Bio
Database

**Comment by mbjones** [comment]
Proposed PeerJ Comp Bio as the venue.
