### ISSUE TITLE
Include oml:ObserationCollection in the mapping

### ISSUE THREAD

**Issue by ramonawalls** [Semantic-Observations/obs-models#23]
Based on some clarifications of OML, we may need to revise our mapping diagram so that oboe:Observation mapps to oml:ObservationCollection rather than oml:Observation. Much of this discussion tool place in an email thread, which I will paste below.

**Comment by ramonawalls** [comment]
Hi Simon,

Matt, Mark, Rob and I are here at ESA working on the ontology alignment. We just took a quick look at your most recent version of the OML paper on SWJ, and noticed that in listing 6, you say that oboe-core:Measurement is equivalent to OML:Observation. However, the VUE diagram we made at our meeting indicates that oboe-core:Observation is an equivalent class to OML:Observation. We were wondering if maybe the listing 6 was written before our meeting, or if you have changed your mind about the alignment since we met.

Ramona

**Comment by ramonawalls** [comment]
Hi Ramona –
I guess I changed my mind (though I thought that was already in the wind in the meeting). O&M Observation is at the lowest level of aggregation, which I think corresponds to oboe:Measurement?

O&M v1 had a formal Observation Collection class. We dropped it in v2 as it was not clear how it was different to a generic Feature Collection.

My thinking on this has subsequently evolved (in response to conversations like this), and I would now re-instate Observation Collection, with the purpose of enabling a common featureOfInterest|observedProperty|procedure|unit-of-measure to apply to all its members. I believe oboe:Observation is effectively one case of O&M v3 Observation Collection (v3 is notional at present … and is likely to appear first in OM-JSON J ).

I will probably upgrade om-lite as well, so in our alignment we can maybe anticipate this (though perhaps add a comment to hedge).

oboe:Measurement rdfs:subClassOf oml:Observation ;
       rdfs:comment “feature of interest from parent collection” .

oboe:Observation rdfs:subClassOf oml:ObservationCollection ;
   rdfs:comment “An observation collection with a common feature of interest, phenomenonTime, …” .

Make sense? (I hope I got this all the right way round.)

Simon

**Comment by ramonawalls** [comment]
Thanks for clarifying. I understand your reasoning - if an oboe:Observation can have many measurements, then it would not map to oml:Observation is each oml:Observation can only have a single output result. In that case, mapping oboe:Observation to oml:ObservationCollection makes more sense.

However, I am not totally comfortable with directly mapping mapping oboe:Observation to oml:ObservationCollection and oboe:Measurement to oml:Observation, because I think that confounds the output of the observing process (the Measurement) with the process of doing the observing/measuring. Others may disagree with me, but I think this distinction is crucial for any general model of observations. I see that both oml:Observation and oboe:Measurement have a property (result and has_value, respectively) that point to "any" so I guess the validity of the mapping depends on the meaning of those two properties.

[unrelated text cut]

Ramona

**Comment by ramonawalls** [comment]
In O&M we call the output of the observing process the ‘result’, and the re-usable procedure used in making the observation the ‘procedure’. The once-off event when the procedure was used to generate this result is the ‘Observation’ – it has a ‘result-time’ to record when it was completed, the existence of which emphasizes the event-ness of an ‘Observation’. The range of ‘result’ is Any in order to accommodate the variety of observation types, but typically it will be a quantity value (measure, scaled number) or count or classification (e.g. taxon).

My take on observation-collection is that at its most basic it is just a bag or container. But usually it will be consistent on one or more of the key axes: feature-of-interest, procedure, observed-property, phenomenon-time, or result-time. Thus you might associate any of these with the container with the implication that it provides a common value for all members of the collection for this property.

In OBOE I think each oboe:Observation is composed of a set of oboe:Measurements of different variables determined using different protocols, possibly with slightly different result-times, but on a single entity with the intention that it represent its state at a single time. In om-lite this would be an Observation-Collection with a common feature-of-interest and phenomenon-time, whose member Observations have different observed-properties, procedures and result-times.

I’ve added Observation Collection class to om-lite so my intention is clear.

See http://def.seegrid.csiro.au/ontology/om/om-lite#ObservationCollection

Simon

**Comment by ramonawalls** [comment]
Thanks, Simon! See my responses in line.

After I send this, I am going to copy this thread to an issue on our repository, so we have a record of it.

Ramona

---

Ramona L. Walls, Ph.D.
Scientific Analyst, The iPlant Collaborative, University of Arizona
Research Associate, Bio5 Institute, University of Arizona
Laboratory Research Associate, New York Botanical Garden

On Tue, Aug 18, 2015 at 6:20 AM, Simon.Cox@csiro.au wrote:

```
Hi Ramona –

In O&M we call the output of the observing process the ‘result’, and the re-usable procedure used in making the observation the ‘procedure’. The once-off event when the procedure was used to generate this result is the ‘Observation’ – it has a ‘result-time’ to record when it was completed, the existence of which emphasizes the event-ness of an ‘Observation’. The range of ‘result’ is Any in order to accommodate the variety of observation types, but typically it will be a quantity value (measure, scaled number) or count or classification (e.g. taxon). 
```

[RW] Perfect. This aligns well with my thinking, and I hope with Matt and Mark's as well.  

```
My take on observation-collection is that at its most basic it is just a bag or container. But usually it will be consistent on one or more of the key axes: feature-of-interest, procedure, observed-property, phenomenon-time, or result-time. Thus you might associate any of these with the container with the implication that it provides a common value for all members of the collection for this property. 
```

[RW] Makes sense. In BCO, we would just have one larger observation process that can have other, more granular observation processes as parts. This is similar to observation-collection, in that the larger observation could be based on similar axes.

```
In OBOE I think each oboe:Observation is composed of a set of oboe:Measurements of different variables determined using different protocols, possibly with slightly different result-times, but on a single entity with the intention that it represent its state at a single time. In om-lite this would be an Observation-Collection with a common feature-of-interest and phenomenon-time, whose member Observations have different observed-properties, procedures and result-times.
```

[RW] This is similar to my understanding of OBOE, but the issue for mapping is what it means to be "composed of" Measurements. I thought an outcome of our mapping exercise was that an oboe:Observation could as parts have many measurement processes, each of which can follow a protocol and has an oboe:Measurement as an output. Matt and Mark, please chime in if  you disagree with this interpretation.

**Comment by dr-shorthair** [comment]
> an oboe:Observation could as parts have many measurement processes, each of which can follow a protocol and has an oboe:Measurement as an output.  

I understand it this way: "an oboe:Observation could as parts have many measurement objects (events) which are called oboe:Measurements. Each oboe:Measurement follows a protocol (process), and has an value (scaled number or word) as an output (or result).  "

**Comment by ramonawalls** [comment]
That is pretty close to how I understand it, except that it is the measurement object (an Event) that would follow the protocol. The oboe:Measurement would follow some oboe:Standard

**Comment by mbjones** [comment]
oml:ObservationCollection is now in the mapping and the figure.
